---
stages:
  - test
image: debian:bookworm

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes git clitest todotxt-cli tox
    python3-docutils flake8 python3-bs4 python3-requests python3-marshmallow
    python3-appdirs python3-argcomplete python3-pdfminer python3-html5lib
    python3-recipe-scrapers python3-yaml

test:
  script:
    - tox run-parallel -e ALL
