---
name: run-tests
on: [push]
jobs:
  run-tox:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Setup Python
        with:
          python-version: 3.11
      - name: Update deb package index
        run: apt-get --quiet update --yes
      - name: Install deb-packages
        run: apt-get --quiet install --yes git clitest todotxt-cli tox
          python3-docutils flake8 python3-bs4 python3-requests
          python3-marshmallow python3-appdirs python3-argcomplete
          python3-pdfminer python3-html5lib python3-recipe-scrapers
          python3-yaml
      - name: Run tox
        run: tox run-parallel -e ALL
